[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Indigo User Manual"
authors = [{name = "SoteriaSec", email = "contact@soteriasec.io"}]
dynamic = ["version", "description"]
